#!/usr/bin/env ruby
require 'rubygems'
require 'bundler/setup'
require 'rainbow'

COLOURS = %i[
  black
  brown
  red
  orange
  yellow
  green
  blue
  violet
  gray
  white
  gold
  silver
  __blank__
].freeze

EXPONENTS = (0..9).to_a + [-1, -2]
MULTS = EXPONENTS.map { |p| 10**p }

TOLERANCE_VALUES = {
  1 => 1,
  2 => 2,
  5 => 0.5,
  6 => 0.25,
  7 => 0.1,
  10 => 5,
  11 => 10,
  12 => 20
}.freeze
TOLERANCES = TOLERANCE_VALUES.keys.freeze

def random_code
  [
    (1..9).to_a.sample,
    (0..9).to_a.sample,
    (0..9).to_a.sample,
    (0..11).to_a.sample,
    TOLERANCES.sample
  ]
end

def to_colours_names(code)
  COLOURS.values_at(*code)
end

def map_colour(colour)
  # For some reason the gold colour looks more like yellow and vice-versa
  {
    yellow: :gold,
    gold: :yellow
  }.fetch(colour, colour)
end

def render_band(str, colour)
  return str if colour == :__blank__
  Rainbow(str).bg(map_colour(colour))
end

def render_bands(colours)
  colours
    .each_with_index
    .map { |c, i| [c, colours.size - 1 == i] }
    .map { |colour, is_tolerance| render_band(is_tolerance ? '%' : ' ', colour) }
end

def render_code(code)
  body = Rainbow('|').color(:lightblue)
  wire = Rainbow('———').color(:darkgray)
  names = to_colours_names(code)
  bands = render_bands(names)
  colour_hint = " (#{names.join(' ')})"

  [wire, body, bands.join(body), body, wire, colour_hint].join
end

def render_key
  digits = COLOURS[0..9].each_with_index.map { |c, i| render_band(i, c) }.join(' ')
  multipliers = EXPONENTS
                .map { |exponent| format('10^%d', exponent) }
                .each_with_index
                .map { |s, i| render_band(s, COLOURS.fetch(i)) }
                .join(' ')
  tolerances = TOLERANCE_VALUES
               .map { |index, value| render_band("#{value}%", COLOURS[index]) }
               .join(' ')
  "Digits:      #{digits}\nMultipliers: #{multipliers}\nTolerances:  #{tolerances}"
end

def format_as_ohms(value)
  return '0Ω' if value == 0.0
  [[10**9, 'G'], [10**6, 'M'], [10**3, 'K'], [10**0, '']].each do |denominator, postfix|
    result = value / denominator
    return format('%g%s', result, postfix) if result >= 1.0
  end
end

def render_outcome(answer, response)
  if response == answer
    puts "#{Rainbow('CORRECT').green} #{answer}Ω"
  else
    puts Rainbow('WRONG').red
    puts "ANS: #{Rainbow(answer).green}Ω, YOURS: #{Rainbow(response).red}Ω"
  end
end

def code_to_number(code)
  ((code[0] * 100 + code[1] * 10 + code[2]) * MULTS[code[3]]).to_f
end

def code_to_str(code)
  number = code_to_number(code)
  format_as_ohms(number)
end

def parse_response(answer)
  answer.strip.upcase
end

def prompt(code)
  puts render_code(code)
  print '? '
  parse_response(gets)
end

begin
  puts render_key
  puts

  10.times do
    code = random_code
    answer = code_to_str(code)
    response = prompt(code)
    puts render_outcome(answer, response)
    puts
  end
rescue Interrupt
  puts
  puts 'Bye!'
end
